#Site
title: Tinper
description: Tinper官网
author: onvno
email: 

# Render模板渲染
url: http://tinper.org
include: ./partial/
# data:
#   package.html: ../data/package/index.json
data_default: true
data_exclude:

# Directory目录
root: /
target: dist

# layout布局
source: src
layout:
    main:
      - 'package/package.html'
      - '*/index.html'